In [1]:
import pandas as pd
data=pd.read_excel('root.xlsx')
data.head()

Text      Target
0  reserve bank forming expert committee based in...  Blockchain
1          director could play role financial system  Blockchain
2  preliminary discuss secure transaction study r...  Blockchain
3  security indeed prove essential transforming f...  Blockchain
4  bank settlement normally take three days based...  Blockchain

In [2]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\NIVAS\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [3]:
data['Text'].dropna(inplace=True)

In [4]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
corpus=[]
for i in range(0,len(data)):
    rev=re.sub('[^a-zA-Z]',' ',str(data['Text'][i]))
    rev=rev.lower()
    rev=rev.split()
    rev=[ps.stem(word) for word in rev if not word in stopwords.words('english')]
    rev=' '.join(rev)
    corpus.append(rev)

In [5]:
corpus

['reserv bank form expert committe base institut develop research bank technolog studi approach distribut ledger technolog help support shift',
 'director could play role financi system',
 'preliminari discuss secur transact studi research payment',
 'secur inde prove essenti transform financi system part effort move away heavi relianc cash base',
 'bank settlement normal take three day base payment verif technolog take less tier secur',
 'agarw head bank',
 'sever data secur regulatori oversight would need wide financi system',
 'relev transact regist avail publicli sequenti record serv effect tool transact settlement among differ payment chain chief risk offic global busi',
 'technolog need transact intermediari clearinghous financi establish thu quick secur inexpens',
 'seven bank morgan chase alreadi support certain cross border fortun',
 'meanwhil bank digit divis har technolog accord news',
 'bank reportedli creat posit chief technolog digit offic',
 'offic report directli charg 

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,ngram_range=(1,3))
x=cv.fit_transform(corpus).toarray()

In [7]:
x.shape
y=data['Target']
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [8]:
cv.get_feature_names()[:30]

['abandon',
 'abid',
 'abil',
 'abl',
 'abl access',
 'abl handl',
 'abl make',
 'abl offer',
 'abroad',
 'absenc',
 'absolut',
 'absorb',
 'abstract',
 'abund',
 'academ',
 'acceler',
 'accept',
 'access',
 'access bank',
 'access control',
 'access credit',
 'access credit inform',
 'access data',
 'access digit',
 'access financ',
 'access financi',
 'access financi servic',
 'access formal',
 'access inform',
 'access manag']

In [9]:
cv.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.int64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': 5000,
 'min_df': 1,
 'ngram_range': (1, 3),
 'preprocessor': None,
 'stop_words': None,
 'strip_accents': None,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'vocabulary': None}

In [10]:
count_df=pd.DataFrame(x_train,columns=cv.get_feature_names())

In [11]:
count_df.head()

abandon  abid  abil  abl  abl access  abl handl  abl make  abl offer  \
0        0     0     0    0           0          0         0          0   
1        0     0     0    0           0          0         0          0   
2        0     0     0    0           0          0         0          0   
3        0     0     0    0           0          0         0          0   
4        0     0     0    0           0          0         0          0   

   abroad  absenc  ...  yahoo  year  year year  yield  york  york time  young  \
0       0       0  ...      0     0          0      0     0          0      0   
1       0       0  ...      0     0          0      0     0          0      0   
2       0       0  ...      0     0          0      0     0          0      0   
3       0       0  ...      0     0          0      0     0          0      0   
4       0       0  ...      0     0          0      0     0          0      0   

   younger  zambia  zero  
0        0       0     0  
1        0       0     0  
2        0       0     0  
3        0       0     0  
4        0       0     0  

[5 rows x 5000 columns]

In [12]:
count_df = pd.DataFrame(x_train, columns=cv.get_feature_names())
count_df.head()

abandon  abid  abil  abl  abl access  abl handl  abl make  abl offer  \
0        0     0     0    0           0          0         0          0   
1        0     0     0    0           0          0         0          0   
2        0     0     0    0           0          0         0          0   
3        0     0     0    0           0          0         0          0   
4        0     0     0    0           0          0         0          0   

   abroad  absenc  ...  yahoo  year  year year  yield  york  york time  young  \
0       0       0  ...      0     0          0      0     0          0      0   
1       0       0  ...      0     0          0      0     0          0      0   
2       0       0  ...      0     0          0      0     0          0      0   
3       0       0  ...      0     0          0      0     0          0      0   
4       0       0  ...      0     0          0      0     0          0      0   

   younger  zambia  zero  
0        0       0     0  
1        0       0     0  
2        0       0     0  
3        0       0     0  
4        0       0     0  

[5 rows x 5000 columns]

In [13]:
from sklearn import metrics
import numpy as np
import itertools
from sklearn.svm import SVC
sv_clf=SVC(probability=True,kernel='linear')
sv_clf.fit(x_test,y_test)
pred=sv_clf.predict(x_test)
score=metrics.accuracy_score(y_test,pred)
print("accuracy: %0.3f" % score) 
cm=metrics.confusion_matrix(y_test,pred)
print(cm)


accuracy: 0.941
[[ 384    0    0    0   67    0    0    0    0    0    0]
 [   6  259    1    0   20    0    0    0    0    0    0]
 [   5    0  502    0   33    0    0    1    0    0    0]
 [   1    0    1   52    4    0    0    0    0    0    0]
 [   2    1    4    0 1704    0    0    0    0    0    0]
 [   1    0    0    0   10  185    0    0    0    0    0]
 [   4    0    0    0   26    0  179    0    0    1    1]
 [   5    0    0    0   40    0    0  397    0    0    0]
 [   0    0    0    0    7    0    0    0  131    0    0]
 [   0    1    1    0    7    0    0    0    0  166    0]
 [   5    0    0    0   15    0    0    0    0    0  312]]


In [14]:
pred

array(['FinTech', 'Robo Advising', 'Cyber Security', ..., 'FinTech',
       'Robo Advising', 'FinTech'], dtype=object)

In [15]:
from sklearn.metrics import f1_score
z=f1_score(y_test,pred,average=None)
print(z)

[0.88888889 0.94698355 0.95619048 0.94545455 0.935236   0.97112861
 0.91794872 0.9452381  0.9739777  0.97076023 0.96744186]


In [ ]:
import matplotlib.pyplot as plt  
from sklearn.metrics import plot_confusion_matrix
from sklearn.svm import SVC
sv_clf.fit(x_train, y_train)
plot_confusion_matrix(sv_clf, x_test, y_test)  
plt.show()  